### ISSUE TITLE
Still gaps between windows even though gaps are set to 0

### ISSUE THREAD

**Issue by ninja542** [glazerdesktop/GlazeWM#329] opened 2023-06-09 16:19 UTC
Latest release

<img width="960" alt="image" src="https://github.com/lars-berger/GlazeWM/assets/18501292/ebd74a8d-8362-4db4-aa04-d76142b6d563">

I set both gaps to be 0 but there is still a gap between windows?

Thank you

Edit: My bad, looked up the other issue. I am confused though, chrome is not electron app so it should have the standard 7px invisible border that gets corrected right?

**Comment by HolbyFPV** [comment] 2023-09-18 00:40
Closing as duplicate of #33

I've personally seen this with a variety of different apps that come from different frameworks.  So the issue is not strictly electron.  Sadly there really isn't a consistent way to determine if an app will behave like this.

**Closed by HolbyFPV** 2023-09-18 00:40 UTC
