### ISSUE TITLE
windows created by WSL2 don't work

### ISSUE THREAD

**Issue by lucvlaming** [glazerdesktop/GlazeWM#307] opened 2023-05-02 10:22 UTC
i'm running intellij via debian on WSL2. whenever glazewm is active, the contents of the intellij windows won't show. when i exit glazewm and then start intellij it all works. 

i tried adding those windows to the "ignore" part, but somehow i can't seem to make that work either.

any suggestions?

**Comment by lucvlaming** [comment] 2023-05-02 10:48
i tried now running with x410 (https://x410.dev/) and that at least works (compared to the normal RDP based approach). however the windows are still not managed.

**Comment by nvrprfct** [comment] 2023-05-03 20:46
running glazewm as administrator?

**Comment by lucvlaming** [comment] 2023-05-08 08:12
i tried both. neither helped much :(

**Comment by HolbyFPV** [comment] 2023-09-17 19:28
Duplicate of #44.  

Closing this to keep all the discussion in one place.

**Closed by HolbyFPV** 2023-09-17 19:28 UTC
