### ISSUE TITLE
alt-shift-q'ing out of windows explorer *often* irreversibly freezes glaze-wm 

### ISSUE THREAD

**Issue by marko-z** [glazerdesktop/GlazeWM#419] opened 2023-09-30 18:02 UTC
Not sure what hte conditions have to be, but it happens often and is incredibly annoying (have to kill glaze-wm in task manager at which point I lose access to all the open windows - not sure if I can always bring them all back by reopening glaze-wm, in either case if I'm successful I then have to migrate them to correct workspaces again)

**Comment by lars-berger** [comment] 2023-10-01 09:53
Is this on the latest release (2.0.03)? Windows 10 or 11? 

I haven't been able to reproduce this with my setup. Could you also share your `config.yaml` and `errors.log` (if it exists, it'll be next to the config file)?

**Comment by phisko** [comment] 2023-10-01 17:50
I've had the same issue every now and then, on the latest release, Windows 11. I don't have an `errors.log` right now, but I use Glaze on multiple PCs so I'll check my work machine tomorrow

**Comment by phisko** [comment] 2023-10-02 05:25
[errors.log](https://github.com/glazerdesktop/GlazeWM/files/12779873/errors.log)

Here's one, but it doesn't look like any of the errors relate to this

**Comment by mikkelrask** [comment] 2023-10-02 17:27
Yeah, happens for me as well. All of the sudden Glaze becomes unresponsive, and no no errors are to find in the logs. Like phisko, I also experience the behavior at random when `alt`+`shift`+`q`'ing, just as it (_for me at least_) also happens sometimes at random when clicking the workspace names with mouse. Never when you're just browsing, or using a single app, but when you either kill one, switch between apps or workspaces. 

I really love using GlazeWM, when at work, since here i'm a forced windows user. But this happens on the daily for me, and basicly a complete reboot of the computer is needed afterworth, since If I just force close Glaze through the task manager, all the apps that were running on other workspaces than the one active when Glaze crashed, arent available through the task bar, and are not in their usual workspace in the newly opened instance. Basicly they becomes a type "zombie processes", that just exist in the background, if not closed with the task manager, as well, hence the reboot, in my case. 

I have like already mentioned verified that there is nothing in my logs about this, but if there is anything else I can do to help investigating this, please just let me know. !

At first I thought it was some sort of memory issue, since I do work my work laptop pretty hard, and it _is_ pretty weak, but it also happens randomly when I use it on my workstation desktop with quadripple the amount of ram - 64GB, which I don't believe is below the min-requirements for glaze .😄

**Comment by phisko** [comment] 2023-10-02 18:24
It's not daily for me, and only occurs with Explorer windows. You may have a separate issue.

As for the "zombie processes", the latest versions of Glaze include a fix for that which should automatically restore all windows when Glaze is forcefully killed.

**Comment by localgrr** [comment] 2023-10-18 22:41
I get the same issue in Windows 11. What a shame, I was really enjoying this but it freezes for me often. No error. Release 2.0.3

**Comment by localgrr** [comment] 2023-10-24 11:28
I have this theory that maybe it's not crashing but it's focusing on a popup or alert that's in the background. I haven't used windows enough recently to test this theory, but that was the solution in a couple of instances.

**Comment by wis** [comment] 2023-12-10 17:39
The `close` command, (by default keybound to `Alt+Shift+Q`)<sup>[1]</sup> killed my whole Chrome process, instead of closing the active window it killed the main process of Chrome. Luckily I have restore tabs on startup of Chrome, also luckily I use [Kanata](https://github.com/jtroo/kanata/) to key bind my commands, and only use the GlazeWM config to bind to a intermediary shortcuts like `Ctrl+Shift+Alt+F24` and in Kanata I bind whatever I want to "press" such shortcuts, so I no longer use the `close` command and just bind to `Alt+F4` in Kanata.

[1] https://github.com/glazerdesktop/GlazeWM/blob/f29274438bdb64e06c97326207d79b3fa68f3455/GlazeWM.App/Resources/sample-config.yaml#L175-L176

**Closed** 2023-12-19 12:25 UTC
Labels: bug

**Comment by aaronedev** [comment] 2024-07-07 12:11
does this issue occur for anyone else still using win11? happens quite frequently especially when using launching ableton for some reason.
